name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurer AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    # 3. Construire l'image Docker
    - name: Build Docker image
      run: |
        docker build -t app_rjo .

    # 4. Déployer l'image Docker sur Elastic Beanstalk
    - name: Deploy Docker image to Elastic Beanstalk
      run: |
        # Initialiser Elastic Beanstalk pour utiliser Docker
        eb init -p docker app_rjo_dock --region eu-west-1  # Remplacez "my-app" par le nom de votre application Elastic Beanstalk
        
        # Déployer avec Elastic Beanstalk
        eb deploy --region eu-west-1