name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main  # Déclenche le pipeline à chaque push sur la branche 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Vérifier le code source
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Configurer AWS CLI
    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    # 3. Installer EB CLI via pip
    - name: Install EB CLI
      run: |
        python -m pip install --upgrade pip
        pip install awsebcli

    # 4. Installer les dépendances Python
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt

    # 5. Déployer sur Elastic Beanstalk
    - name: Deploy to Elastic Beanstalk
      run: |
        eb init -p python-3.8 app_rjo2 --region eu-west-1
        eb deploy